### ISSUE TITLE
[Баев] Связь с API на фронте: изменение дерева

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#141]

**Comment by BaevDaniil** [comment]
Реализована выгрузка квеста из базы данных и отображение его в конструкторе, изменения текста любого блока с отправкой данных на сервер, также изменение формулировок ответов и начисляемые баллы. Частично реализовано добавление новых блоков. Протестировано сохранение. Частично реализовано отслеживание связей между блоками.
