### ISSUE TITLE
[01.05][Шварц] Рефакторинг редактора movement (внешний вид)

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#248]

**Comment by BaevDaniil** [comment]
[] Изменить позиционирование карты на текущее положение пользователя, если точка еще не указана, и на точку в противном
[] Добавить отметку точки на карту
[] Добавить визуальное отображение радиуса
[] Избавиться от полей формы "координаты" и "радиус" для того, чтобы не было скрола в окне
[] Избавиться от отображения координат
[] Добавить выбор радиуса в информацию о точке на самой карте (если не будет слишком мелко, иначе разместить поверх карты в нижнем правом углу)
[] В любом случае поле "радиус" должно быть числового типа (а не текстового, как сейчас)
