### ISSUE TITLE
[Шварц][17.03] Создание таблиц БД

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#46]
Написать скрипт на SQL с созданием таблиц в sheme.sql

**Comment by IlyaP01** [comment]
Приконнекть issue на гитхабе и добавь меня в ревью

**Comment by IlyaP01** [comment]
![image.png](https://images.zenhubusercontent.com/620abc976a9232fc6ff6b387/0b6e77b3-d9c9-4ef7-88dc-f71005f1012f) Нужно исправить схему и скрипт
