### ISSUE TITLE
[Воротников] Преимущества перед аналогами

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#48]

**Comment by mashaverdina** [comment]
Ссылка urban quest ведет на surprise me
Сам документ тяжело читать, я бы подумала над тем, чтобы сделать его в виде таблицы: по одной оси продукты, по другой - фичи.
Если не таблицей:

- стоит использовать одинаковую терминологию при сравнении, например, как я поняла "There is no ability to create quest "for friends"." и "There is ability to create private quests" - это про одно и то же, но чтобы разобраться требуется больше времени, чем хотелось бы.
- "There is no place for all created and safe quests" - это слишком тяжело понять, нужно переписать понятнее. (Нельзя опубликовать свой квест? Нет просмотра публичных квестов других пользователей? как-то еще?)
