### ISSUE TITLE
[Чевыкалов] Правки в бд

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#75]

**Comment by AleksandrShvartz** [comment]
Обновить схему бд. Заменить описание(расписать неочевидные моменты). Отметить на схеме типы полей(not null/уникальное поле. Пнуть меня создать таблицы.

**Comment by IlyaP01** [comment]
![image.png](https://images.zenhubusercontent.com/620abc976a9232fc6ff6b387/50e26c55-1264-4c68-aeb4-7ee737b8ab55) Нужно поправить
