### ISSUE TITLE
[Воротников] Инструкция по запуску для пользователей (бот)

### ISSUE THREAD

**Issue by aVorotnikov** [Quest-maker-team/quest-maker#90]

**Comment by mashaverdina** [comment]
Ссылку на бот хочется видеть на главной странице, наверное где-то в описании

**Comment by mashaverdina** [comment]
Ссылку на бот хочется видеть на главной странице, наверное где-то в описании

**Comment by mashaverdina** [comment]
> To play quests user must use telegram bot @QuestMakerBot
must слишком сильный глагол для пользователей в этом контексте. Если очень хочется, можно написать bot is required. Я бы советовала should, но он, возможно, полностью не передает тот смысл, который вы закладывали. Возможно, в качестве нейтрального варианта подойдет "To play quests we provide to users...". Или что-то такое. ought to?

> In bot player need to choose quest and then quest session starts.
need тут тоже не совсем подходит по смыслу. Я бы ставила should choose
